version: '3.3'

services:

    ex-wiremock:
      container_name: ex-wiremock
      image: rodolpheche/wiremock:2.25.1
      restart: always
      volumes:
        - .:/home/wiremock
      ports:
        - 9090:8080